#lang scheme

;;; List of possible registers to adress
;;; TODO: add utils to iterate ofer them all as well as classification routines

(define (r0) 0)
(define (r1) 1)
(define (r2) 2)
(define (r3) 3)
(define (r5) 4)
(define (r6) 5)
(define (r7) 6)

(define al r0)
(define cl r1)
(define dl r2)
(define bl r3)
(define ah r4)
(define ch r5)
(define dh r6)
(define bh r7)

(define ax r0)
(define cx r1)
(define dx r2)
(define bx r3)
(define sp r4)
(define bp r5)
(define si r6)
(define di r7)

(define eax r0)
(define ecx r1)
(define edx r2)
(define ebx r3)
(define esp r4)
(define ebp r5)
(define esi r6)
(define edi r7)

(define es r0)
(define cs r1)
(define ss r2)
(define ds r3)
(define fs r4)
(define gs r5)

(define st0 r0)
(define st1 r1)
(define st2 r2)
(define st3 r3)
(define st4 r4)
(define st5 r5)
(define st6 r6)
(define st7 r7)

(define mm0 r0)
(define mm1 r1)
(define mm2 r2)
(define mm3 r3)
(define mm4 r4)
(define mm5 r5)
(define mm6 r6)
(define mm7 r7)

(define xmm0 r0)
(define xmm1 r1)
(define xmm2 r2)
(define xmm3 r3)
(define xmm4 r4)
(define xmm5 r5)
(define xmm6 r6)
(define xmm7 r7)

(define cr0 r0)
(define cr1 r1)
(define cr2 r2)
(define cr3 r3)
(define cr4 r4)

(define dr0 r0)
(define dr1 r1)
(define dr2 r2)
(define dr3 r3)
(define dr3 r4)
(define dr3 r5)
(define dr3 r6)
(define dr4 r7)

(define tr0 r3)
(define tr1 r4)
(define tr2 r5)
(define tr3 r6)
(define tr4 r7)
